### ISSUE TITLE
Solar panel cannot be put into container

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Surface-Experiment-Pack#11]
Appears to be related to tweakscale

**Comment by cake-pie** [comment]
KIS won't stack parts that have modules that it doesn't recognize as stackable. ihsoft/KIS#205
Not SEP's fault, caused by other mod interaction with KIS.

**Comment by CobaltWolf** [comment]
Can I close this then?

**Comment by cake-pie** [comment]
I did check (in KSP 1.2.2, this was before 1.3 came out) that SEP solar panel is working fine; it can be:
- put/stacked in container in Editor
- removed from container in Flight
- put/stacked in container in Flight

So as far as I can tell, there's nothing wrong with how SEP has configured the part for KIS, and I think this issue can be closed. If it does crop up again then we can take another look.

In general, when some other mod interferes with KIS functionality, that's something that has to be resolved between them. SEP is just collateral damage when that happens.
