### ISSUE TITLE
Not all experiments fixed.  Some still explode, some still break loose.

### ISSUE THREAD

**Issue by Ruedii** [CobaltWolf/Surface-Experiment-Pack#19]
Some experiments still explode when mounted to the ground.  Many still break loose from the ground too easily. 

I've Identified the later problem, and have my suspicious on the former.

I may take a look at the cfg files and see if I can whip up a patch.

**Comment by CobaltWolf** [comment]
Sure, that would be awesome! I believe one or two of the parts slipped through the cracks and didn't get their static attach strength fixed.
