### ISSUE TITLE
Some parts (e.g. power plug) not available in VAB

### ISSUE THREAD

**Issue by Florianer** [CobaltWolf/Surface-Experiment-Pack#24]
Hi. Maybe I messed up something. Mods are installed with ckan. Tech tree node electricity includes the AKI Power Transfer Conduit. Also unlocked it. In VAB/SPH it is not available. Not via category nor via name search. 
After googling and looking around I found the `SurfaceExperimentPackage/Parts/SEP_plug.cfg`. History showed, that category was and is set to none. But if I change it to `category = Utility`, I can find the part in the VAB/SPH. 
Did I break stuff or need the cfg an update? As said, I installed all (42) mods via ckan for KSP 1.2.1. I also deleted and reinstalled all mods, switched from career save game to newly created sandbox. Didn't do the trick. I saw YT mod showcase with the plug available.
I also did a `grep --include=*.cfg --exclude-dir=Squad -rnw '.' -e "category = none"` resulting in `./SurfaceExperimentPackage/Parts/SEP_Screwdriver.cfg:15:	category = none
./SurfaceExperimentPackage/Parts/SEP_CentralStation.cfg:115:	category = none`
I guess, Central Station is just the sub part, but the Screwdriver is also missing. I just got the wrench. 

Besides you mod, there are a lot of category = none hits and I did not looked them up. Anyway, is this a confirmable bug?

**Comment by DMagic1** [comment]
Should be fixed in 2.1.2. All parts were moved into proper categories, and this is compatible with the latest version of KIS for the EVA category.

Changing the categories yourself is also fine.
