### ISSUE TITLE
Cannot open the menu for the plugs

### ISSUE THREAD

**Issue by Vimuee** [CobaltWolf/Surface-Experiment-Pack#38]
I installed this mod with only KAS, KIS and module manager, but I found that though every other thing is fine, I cannot open the menu of the plugs, means I cannot give power to my devices. Did the mod changed the way of linking the plugs?
[KSP.log](https://github.com/CobaltWolf/Surface-Experiment-Pack/files/1327808/KSP.log)

**Comment by DMagic1** [comment]
It looks like you are using the KAS 1.0 Beta, that is not supported by SEP, you need the old KAS version. You can probably use both together at the same time (they are two separate mods that are confusingly named the same thing...), but SEP requires the old version.
